# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DrawGraph' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DrawGraph
  pod 'Charts', '~> 3.0'

  target 'DrawGraphTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DrawGraphUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
